title: Main Portfolio for1
description: 제 웹 개발 포트폴리오입니다

# User settings
username: jjobfor1-ux
user_title: 모험가
user_description: 안녕하세요! 저는 만드는 걸 좋아하는 초보 모험가입니다. 제 프로젝트들을 구경해보세요 :)
email: jjobfor1@gmail.com
github_username: jjobfor1-ux

# Google Analytics (지금은 비워두세요)
google-analytics:
  id: ""
